### ISSUE TITLE
Django Project

### ISSUE THREAD

**Issue by sreelakshmig009** [sudip-mondal-2002/HactoberFest21#156]
I want to contribute a Python Django Movie Recommendation System Projects for Hacktoberfest 2021

**Comment by sudip-mondal-2002** [comment]
Sure, go on!!

**Comment by Hacker-sagar1** [comment]
I want to contribute a Python Django Movie Recommendation System Projects for Hacktoberfest 2021

**Comment by sudip-mondal-2002** [comment]
Hey!! If your algo differs from others then yes you're welcome to contribute

**Comment by sreelakshmig009** [comment]
@sudip-mondal-2002 Sorry I couldnt do it on time as I had offline classes. Can you reopen this issue? I want to make a pr now?

**Comment by sreelakshmig009** [comment]
![Screenshot (230)](https://user-images.githubusercontent.com/81172589/136140556-01d3ac22-8bf0-403c-b639-ecc279557dea.png)
This is how the project looks like. Shall I make a PR?
