### ISSUE TITLE
Social media icons

### ISSUE THREAD

**Issue by Rameshchandrapola** [sudip-mondal-2002/HactoberFest21#172]
Hello @sudip-mondal-2002 
As a part of hacktoberfest
can I submit social media icons buttons
## Demo
![social media icons](https://user-images.githubusercontent.com/76244600/135817364-81f80a79-1371-4f88-9e42-250e62d2fce9.gif)

# Thankyou🚀

**Comment by sudip-mondal-2002** [comment]
Sure add the codes for these. You're welcome
